name: Build and Push Docker Images

on:
  push:
    paths:
      - '.github/workflows/**'  # 仅在action文件更新时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
         # target: final   # 仅在 Dockerfile 使用多阶段构建时保留
          tags: |
            localhost/qywx-push:latest

      - name: Push to Aliyun Registry (Ignore failure)
        if: always()  # 无论之前步骤是否失败都执行
        continue-on-error: true
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
        id: aliyun-login

      - name: Push to Aliyun (Ignore failure)
        if: always()
        continue-on-error: true
        uses: docker/build-push-action@v6
        with:
          context: .
        # target: final   # 仅在 Dockerfile 使用多阶段构建时保留
          tags: |
            ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}qywx-push:latest
            ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}qywx-push:1.0
          push: true

      - name: Push to Docker Hub (Ignore failure)
        if: always()
        continue-on-error: true
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        id: dockerhub-login

      - name: Push to Docker Hub (Ignore failure)
        if: always()
        continue-on-error: true
        uses: docker/build-push-action@v6
        with:
          context: .
         # target: final   # 仅在 Dockerfile 使用多阶段构建时保留
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/qywx-push:latest
          push: true
